# Retirez la ligne "version: '3.8'" qui est obsolète

services:
  backend:
    build: ./backend
    ports:
      - "8002:8002"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/gestion_contrat
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    # Ajouter restart pour redémarrer en cas d'erreur
    restart: unless-stopped
    command: ["npm", "run", "dev"]

  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    # Hot-reload pour Next.js
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
